### ISSUE TITLE
Occasionally stops handling requests when concurrentWorkers == 1

### ISSUE THREAD

**Issue by sekogan** [four43/node-express-enqueue#1]
The module randomly stops handling requests when concurrentWorkers is set to 1. All new requests get into the queue until it is overflowed.

I started digging into the problem and discovered that it happens when:
- the worker performs some slow activity and several requests are waiting in the queue,
- the client that sent one of these pending requests aborts it.

In this scenario the onFinished callback is called when the request is still in this.queue. When that request is moved into this.inProgressQueue the whole module gets stuck forever.

Working on a PR.

**Comment by four43** [comment]
Hey thanks for the feedback, looking over this now.

**Comment by four43** [comment]
I'm still hacking on this, having the hardest time getting coverage. I tried to write the test myself to better understand the problem, and because I'm high maintenance. It's still giving me some fits though.

**Comment by four43** [comment]
@sekogan - What node version are you using? As I make updates I want to make sure I don't leave you behind. I'm testing for 4, 6, 8, and 9 right now.

**Comment by sekogan** [comment]
@four43 Sorry, forgot to mention: node 9.1.0 and 9.2.0.

**Comment by four43** [comment]
Oh good, testing for that now. I pushed a v1.0.0 version to npm. Take a look, hopefully this solves your use case.
